import { createInstallationToken, finishCheckRun, getOrCreateCheckRun, getPullRequestDiff, syncFindingReviewComments, upsertPullRequestComment } from "./github";
import { announceDashboardChange } from "./dashboard-change-service";
import { ReviewLeaseLostError } from "./review-errors";
import { runInSandbox, unavailableSandboxResult, type SandboxRunOptions } from "./sandbox";
import { redactSecrets } from "./secret-redaction";
import {
  REVIEW_AI_RESERVE_MS,
  REVIEW_PUBLISH_RESERVE_MS,
  SANDBOX_MIN_BUDGET_MS,
  WORKER_INVOCATION_BUDGET_MS,
} from "./review-invocation-limits";
import { getRepositoryReviewContext } from "./repository-context-service";
import type { ReviewLease } from "./review-queue";
import type { ReviewFinding, ReviewRequest, ReviewResult, SandboxResult } from "./types";
import { findingIdentity } from "./review-event-ledger";
import { formatFindingComment } from "./finding-comment";
import { getInvocationStartedAt } from "./review-invocation-budget";
import { remainingInvocationBudgetMs } from "./openrouter-review-provider";
import { generateRoutedReview } from "./review-route-service";
import { resolveReviewRouteConfig } from "./review-route-config";
import { prepareReviewRouteFromDiff } from "./review-route-preparation";
import { shouldSkipSandboxBuild } from "./review-route-selector";
import { safeReviewPolicy } from "./review-policy";
import { applyReviewPolicyToResult, filterReviewDiff } from "./review-policy-execution";

function formatSandboxLines(sandbox: SandboxResult) {
  if (sandbox.status === "unavailable") {
    return `- ⚠️ Sandbox checks did not run: ${sandbox.unavailableReason ?? "sandbox unavailable"}`;
  }
  return [
    ...sandbox.commands.map((command) => `- ${command.exitCode === 0 ? "✅" : "❌"} \`${command.command}\``),
    ...(sandbox.skippedCommands ?? []).map((label) => `- ⚠️ \`${label}\` skipped (sandbox time budget)`),
  ].join("\n");
}

function formatReview(result: ReviewResult) {
  const icon = result.verdict === "approve" ? "✅" : result.verdict === "request_changes" ? "⛔" : "💬";
  const sandboxLines = formatSandboxLines(result.sandbox);
  const findingLines = result.findings.length ? result.findings.map((finding, index) => {
    const location = finding.file ? ` — \`${finding.file}${finding.line ? `:${finding.line}` : ""}\`` : "";
    const fix = finding.suggestedFix ? `\n\n**Suggested fix:** ${finding.suggestedFix}` : "";
    return `### ${index + 1}. ${finding.title}${location}\n\n**${finding.severity}** · ${finding.explanation}${fix}`;
  }).join("\n\n") : "No material findings.";
  return `## ${icon} Ternary review\n\n${result.summary}\n\n${findingLines}\n\n<details><summary>Sandbox checks</summary>\n\n${sandboxLines}\n\nSandbox: \`${result.sandbox.sandboxId}\` · ${Math.round(result.sandbox.durationMs / 1000)}s\n</details>\n\n---\n<sub>Generated by your internal Ternary review agent.</sub>`;
}

/** Sandbox evidence is best-effort: quota exhaustion, API outages, or a thin time budget degrade to an AI-only review instead of failing the job. */
async function gatherSandboxEvidence(request: ReviewRequest, token: string, options: SandboxRunOptions): Promise<SandboxResult> {
  const remaining = (options.deadlineAt ?? Number.POSITIVE_INFINITY) - Date.now();
  if (remaining < SANDBOX_MIN_BUDGET_MS) {
    return unavailableSandboxResult("skipped to protect the AI review time budget");
  }
  try {
    return await runInSandbox(request, token, options);
  } catch (error) {
    console.error(`Sandbox unavailable for ${request.owner}/${request.repo}#${request.pullNumber}`, error);
    const message = error instanceof Error ? error.message : "Unknown sandbox failure";
    return unavailableSandboxResult(redactSecrets(message).slice(0, 300));
  }
}

export async function runReview(request: ReviewRequest & { id?: string }, lease?: ReviewLease) {
  const invocationStartedAt = getInvocationStartedAt() ?? ("startedAt" in request && typeof request.startedAt === "number" ? request.startedAt : Date.now());
  const policy = request.policy ?? { ...safeReviewPolicy, model: process.env.OPENROUTER_MODEL ?? safeReviewPolicy.model };
  const token = await createInstallationToken(request.installationId);
  await lease?.assertActive();
  const checkPromise = getOrCreateCheckRun(request.owner, request.repo, request.headSha, token, request.id);
  const diffPromise = getPullRequestDiff(request.owner, request.repo, request.pullNumber, token);
  const check = await checkPromise;
  await announceDashboardChange();
  try {
    const diff = await diffPromise;
    const reviewDiff = filterReviewDiff(diff, policy.excludedPaths);
    const routeConfig = resolveReviewRouteConfig();
    const diffPrep = prepareReviewRouteFromDiff(reviewDiff, routeConfig);
    const skipBuild = shouldSkipSandboxBuild(diffPrep, routeConfig);
    const sandboxDeadlineAt = invocationStartedAt + WORKER_INVOCATION_BUDGET_MS - REVIEW_PUBLISH_RESERVE_MS - REVIEW_AI_RESERVE_MS;
    const [sandbox, repositoryContext] = await Promise.all([
      gatherSandboxEvidence(request, token, { skipBuild, deadlineAt: sandboxDeadlineAt }),
      getRepositoryReviewContext(request, token, reviewDiff),
    ]);
    const generated = await generateRoutedReview(
      reviewDiff,
      sandbox,
      repositoryContext.text,
      policy,
      { remainingMs: remainingInvocationBudgetMs(invocationStartedAt) },
    );
    const result = applyReviewPolicyToResult(generated, policy);
    const marker = request.id ? `\n\n<!-- ternary-review-job:${request.id} -->` : "";
    const markdown = `${formatReview(result)}${marker}`;
    await lease?.assertActive();
    await upsertPullRequestComment(request.owner, request.repo, request.pullNumber, token, markdown, request.id);
    await lease?.assertActive();
    if (result.authoritativeFindings !== false) {
      // Stop syncing inline comments shortly before the platform kill; the summary comment above already carries every finding.
      const publishDeadlineAt = invocationStartedAt + WORKER_INVOCATION_BUDGET_MS - 10_000;
      await syncFindingReviewComments(request.owner, request.repo, request.pullNumber, request.headSha, token, result.findings.filter((finding) => finding.file).map((finding) => {
        const findingId = findingIdentity(request, finding);
        return { findingId, body: formatFindingComment(finding, findingId), path: finding.file, line: finding.line };
      }), { deadlineAt: publishDeadlineAt });
    }
    await lease?.assertActive();
    await finishCheckRun(request.owner, request.repo, check.id, token, result.verdict === "approve" ? "success" : result.verdict === "request_changes" ? "failure" : "neutral", "Review complete", markdown, JSON.stringify(result));
    return result;
  } catch (error) {
    if (error instanceof ReviewLeaseLostError) throw error;
    const message = error instanceof Error ? error.message : "Unknown review failure";
    await lease?.assertActive();
    await finishCheckRun(request.owner, request.repo, check.id, token, "failure", "Review failed", message);
    throw error;
  } finally {
    await announceDashboardChange();
  }
}

export function countBlockingFindings(findings: ReviewFinding[]) {
  return findings.filter((finding) => finding.severity === "blocking").length;
}
