import { createInstallationToken, finishCheckRun, getOrCreateCheckRun, getPullRequestDiff, syncFindingReviewComments, upsertPullRequestComment } from "./github";
import { announceDashboardChange } from "./dashboard-change-service";
import { ReviewLeaseLostError } from "./review-errors";
import { runInSandbox } from "./sandbox";
import { getRepositoryReviewContext } from "./repository-context-service";
import type { ReviewLease } from "./review-queue";
import type { ReviewFinding, ReviewRequest, ReviewResult } from "./types";
import { findingIdentity } from "./review-event-ledger";
import { formatFindingComment } from "./finding-comment";
import { getInvocationStartedAt } from "./review-invocation-budget";
import { remainingInvocationBudgetMs } from "./openrouter-review-provider";
import { generateRoutedReview } from "./review-route-service";
import { resolveReviewRouteConfig } from "./review-route-config";
import { prepareReviewRouteFromDiff } from "./review-route-preparation";
import { shouldSkipSandboxBuild } from "./review-route-selector";
import { safeReviewPolicy } from "./review-policy";
import { applyReviewPolicyToResult, filterReviewDiff } from "./review-policy-execution";

function formatReview(result: ReviewResult) {
  const icon = result.verdict === "approve" ? "✅" : result.verdict === "request_changes" ? "⛔" : "💬";
  const sandboxLines = result.sandbox.commands.map((command) => `- ${command.exitCode === 0 ? "✅" : "❌"} \`${command.command}\``).join("\n");
  const findingLines = result.findings.length ? result.findings.map((finding, index) => {
    const location = finding.file ? ` — \`${finding.file}${finding.line ? `:${finding.line}` : ""}\`` : "";
    const fix = finding.suggestedFix ? `\n\n**Suggested fix:** ${finding.suggestedFix}` : "";
    return `### ${index + 1}. ${finding.title}${location}\n\n**${finding.severity}** · ${finding.explanation}${fix}`;
  }).join("\n\n") : "No material findings.";
  return `## ${icon} Ternary review\n\n${result.summary}\n\n${findingLines}\n\n<details><summary>Sandbox checks</summary>\n\n${sandboxLines}\n\nSandbox: \`${result.sandbox.sandboxId}\` · ${Math.round(result.sandbox.durationMs / 1000)}s\n</details>\n\n---\n<sub>Generated by your internal Ternary review agent.</sub>`;
}

export async function runReview(request: ReviewRequest & { id?: string }, lease?: ReviewLease) {
  const invocationStartedAt = getInvocationStartedAt() ?? ("startedAt" in request && typeof request.startedAt === "number" ? request.startedAt : Date.now());
  const policy = request.policy ?? { ...safeReviewPolicy, model: process.env.OPENROUTER_MODEL ?? safeReviewPolicy.model };
  const token = await createInstallationToken(request.installationId);
  await lease?.assertActive();
  const checkPromise = getOrCreateCheckRun(request.owner, request.repo, request.headSha, token, request.id);
  const diffPromise = getPullRequestDiff(request.owner, request.repo, request.pullNumber, token);
  const check = await checkPromise;
  await announceDashboardChange();
  try {
    const diff = await diffPromise;
    const reviewDiff = filterReviewDiff(diff, policy.excludedPaths);
    const routeConfig = resolveReviewRouteConfig();
    const diffPrep = prepareReviewRouteFromDiff(reviewDiff, routeConfig);
    const skipBuild = shouldSkipSandboxBuild(diffPrep, routeConfig);
    const [sandbox, repositoryContext] = await Promise.all([
      runInSandbox(request, token, { skipBuild }),
      getRepositoryReviewContext(request, token, reviewDiff),
    ]);
    const generated = await generateRoutedReview(
      reviewDiff,
      sandbox,
      repositoryContext.text,
      policy,
      { remainingMs: remainingInvocationBudgetMs(invocationStartedAt) },
    );
    const result = applyReviewPolicyToResult(generated, policy);
    const marker = request.id ? `\n\n<!-- ternary-review-job:${request.id} -->` : "";
    const markdown = `${formatReview(result)}${marker}`;
    await lease?.assertActive();
    await upsertPullRequestComment(request.owner, request.repo, request.pullNumber, token, markdown, request.id);
    await lease?.assertActive();
    if (result.authoritativeFindings !== false) {
      await syncFindingReviewComments(request.owner, request.repo, request.pullNumber, request.headSha, token, result.findings.filter((finding) => finding.file).map((finding) => {
        const findingId = findingIdentity(request, finding);
        return { findingId, body: formatFindingComment(finding, findingId), path: finding.file, line: finding.line };
      }));
    }
    await lease?.assertActive();
    await finishCheckRun(request.owner, request.repo, check.id, token, result.verdict === "approve" ? "success" : result.verdict === "request_changes" ? "failure" : "neutral", "Review complete", markdown, JSON.stringify(result));
    return result;
  } catch (error) {
    if (error instanceof ReviewLeaseLostError) throw error;
    const message = error instanceof Error ? error.message : "Unknown review failure";
    await lease?.assertActive();
    await finishCheckRun(request.owner, request.repo, check.id, token, "failure", "Review failed", message);
    throw error;
  } finally {
    await announceDashboardChange();
  }
}

export function countBlockingFindings(findings: ReviewFinding[]) {
  return findings.filter((finding) => finding.severity === "blocking").length;
}
